# Generated by Django 4.1 on 2022-09-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usignup',
        ),
    ]
